# Generated by Django 5.2.4 on 2025-08-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='idHeroApi',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
